---
# tasks file for myvhost
- name: install httpd
  yum:
   name: httpd
   state: latest
- name: create vhost.conf file
  template:
   src: vhost.conf.j2
   dest: /etc/httpd/conf.d/vhost.conf
   owner: root
   group: root
   mode: 0644
  notify: 
   - restart httpd
- name: httpd is started and enabled
  service:
   name: httpd
   state: started
   enabled: yes
- name: copy web contents
  copy:
   src: html/
   dest: "/var/www/vhosts/{{ ansible_facts['hostname'] }}"
