---
- name: print
  hosts: dstest
  tasks:
   - name: adding hostname in etc hosts
     lineinfile:
      path: /root/dstest
#      regexp: '^{{ ansible_facts.ansible_default_ipv4.address }}'
#      line: '{{ ansible_facts.ansible_default_ipv4.address }} {{ ansible_facts.ansible_hostname }}'
      line: '{{ ansible_facts.ansible_default_ipv4.address }}'
      state: present
      notify: reboot_host

  handlers:
   - name: reboot_host
     command: /sbin/shutdown -r +1
     async: 1
     poll: 0
     ignore_errors: true
