---
- name: setting up the baseline for a new build
  hosts: dstest
  remote_user: root
  pre_tasks:
   - name: install libselinux-python
     yum:
      name: libselinux-python
      state: latest
  roles:
   - role: baseline
     package_names:
     - wget
     - telnet
     - sysstat
     service_names:
      - sysstat
      - nfs

