---
- name: test
  hosts: dstest
  vars: 
   data:
    - user0
    - user1
    - user2
   supported_os:
#    - OracleLinux
    - RedhatLinux
   supported_version:
    - "7.3"
   db_packages:
    - mariadb-server
    - MySQL-python
   db_service: mysqld.service


  tasks: 
   - name: test
     shell: | 
      LASTONE=$(cat /root/dsfile)

      if [[ $LASTONE == "ds" ]]; then
       echo this is true
      fi
