---
- name: test
  hosts: dstest
  vars: 
   data:
    - user0
    - user1
    - user2


  tasks: 
   - name: looping items
#     shell: "echo This is item # {{ with_sequence }} {{ item }}"
     shell: "echo This is item {{ item }}"
     loop: "{{ data }}"
     register: item_output
   - name: debugging
     debug: 
      msg: "{{ item_output }}"
