---
- name: set up interval for sysstat
  hosts: dstest
  tasks:
   - name: set up the interval for sysstat for 1 minute
     replace:
      path: /root/dsfile
      regexp: '(\*/10) dosun'
      replace: 'test'
      backup: yes
